export const CREATE_USER="CREATE_USER";
export const RETRIEVE_USERS="RETRIEVE_USERS";
export const UPDATE_USER="UPDATE_USER";
export const DELETE_USER="DELETE_USER";
export const DELETE_ALL_USERS="CREATE_USERS";